### ISSUE TITLE
[TODO] list of pending ports from ngx_http_lua 

### ISSUE THREAD

**Issue by thibaultcha** [openresty/meta-lua-nginx-module#70]
I compiled a list of commits from [ngx_http_lua](https://github.com/openresty/lua-nginx-module) that are not yet ported to this module (excluding the currently opened PRs):

- [ ] openresty/lua-nginx-module@c618d0d (code cache lookup bugfix)
- [ ] openresty/lua-nginx-module@881bf91 (bugfix: prevent resp headers APIs to have \r \n)
- [ ] openresty/lua-nginx-module@246ec8a (refactor: simpler cache key gen)
- [ ] openresty/lua-nginx-module@f45908c (refactor: smaller cache keys)
- [ ] openresty/lua-nginx-module@0c755ed (bugfix: `set_by_lua_file` with NGINX vars)
- [ ] openresty/lua-nginx-module@39c2ead (optimize: code cache lookup)
- [ ] openresty/lua-nginx-module@09484e8 (bugfix: `init_worker_by_lua` mutating main confs)
- [ ] openresty/lua-nginx-module@d3dbc0c (TLS 1.3 session skip)
- [ ] openresty/lua-nginx-module@32dd6a3
- [ ] openresty/lua-nginx-module@59b6430
- [ ] openresty/lua-nginx-module@33a5517
- [ ] openresty/lua-nginx-module@a7afd56 (ngx.pipe with env vars)
- [ ] openresty/lua-nginx-module@28cf5ce (str_replace_char FFI API for regex module)
- [ ] openresty/lua-nginx-module@f87d1f1 (ngx.pipe bugfix)
- [ ] openresty/lua-nginx-module@afeeb84 (ngx.pipe bugfix)
- [ ] openresty/lua-nginx-module@ee47e55a (ngx.pipe bugfix)
- [ ] openresty/lua-nginx-module@761ddca (cosocket conn queue bugfix)
- [ ] openresty/lua-nginx-module@8edb21a (cosocket conn queue bugfix)
- [ ] openresty/lua-nginx-module@b2af4d3
- [ ] openresty/lua-nginx-module@aef03eb (ngx.pipe support)
- [ ] openresty/lua-nginx-module@c2940c1 (cosocket conn queuing)
- [ ] openresty/lua-nginx-module@2fb8f12
- [ ] openresty/lua-nginx-module@248060b
- [ ] openresty/lua-nginx-module@fbb8919
- [ ] openresty/lua-nginx-module@cec2a09
- [ ] openresty/lua-nginx-module@08a9baa
- [ ] openresty/lua-nginx-module@84338ab
- [ ] openresty/lua-nginx-module@f64ec8c
- [ ] openresty/lua-nginx-module@e94f2e5 (segfault in `init_worker_by*` with NGINX >= 1.15.0)
- [ ] openresty/lua-nginx-module@55743ae

**Comment by thibaultcha** [comment]
Currently working locally on porting these changes over to this module.

**Comment by thibaultcha** [comment]
#71 contains all the ports up to ngx_http_lua v0.10.15.
